-- Sequence para Author e Book (conforme annotations sequenceName = "SEQ_TB_BOOK")
CREATE SEQUENCE SEQ_TB_BOOK START WITH 1 INCREMENT BY 1 NOCACHE;

-- Sequence para UserApp
CREATE SEQUENCE SEQ_USER_APP START WITH 1 INCREMENT BY 1 NOCACHE;

-- Sequence para UserBook
CREATE SEQUENCE SEQ_USER_BOOK START WITH 1 INCREMENT BY 1 NOCACHE;

-- Tabela de Status do Usuário
CREATE TABLE USER_STATUS (
    STATUS_ID NUMBER(19) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_USER_STATUS PRIMARY KEY (STATUS_ID)
);

-- Tabela de Gêneros
CREATE TABLE GENRE (
    GENRE_ID NUMBER(19) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_GENRE PRIMARY KEY (GENRE_ID)
);

-- Tabela de Autores
CREATE TABLE AUTHOR (
    AUTHOR_ID NUMBER(19) NOT NULL,
    NAME VARCHAR2(150) NOT NULL,
    BIRTH_DATE DATE,
    COUNTRY VARCHAR2(100),
    CONSTRAINT PK_AUTHOR PRIMARY KEY (AUTHOR_ID)
);

-- Tabela de Usuários da Aplicação
CREATE TABLE USER_APP (
    USER_ID NUMBER(19) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    LOGIN VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    STATUS_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_USER_APP PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USER_APP_LOGIN UNIQUE (LOGIN),
    CONSTRAINT FK_USER_APP_STATUS FOREIGN KEY (STATUS_ID) REFERENCES USER_STATUS(STATUS_ID)
);

-- Tabela de Livros
CREATE TABLE BOOK (
    BOOK_ID NUMBER(19) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    LANGUAGE VARCHAR2(50) NOT NULL,
    ISBN VARCHAR2(20),
    CONSTRAINT PK_BOOK PRIMARY KEY (BOOK_ID),
    CONSTRAINT UK_BOOK_ISBN UNIQUE (ISBN)
);

-- Tabela de Relacionamento Livro x Autor (ManyToMany)
CREATE TABLE BOOK_AUTHOR (
    BOOK_ID NUMBER(19) NOT NULL,
    AUTHOR_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_BOOK_AUTHOR PRIMARY KEY (BOOK_ID, AUTHOR_ID),
    CONSTRAINT FK_BOOK_AUTHOR_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    CONSTRAINT FK_BOOK_AUTHOR_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
);

-- Tabela de Relacionamento Livro x Gênero (ManyToMany)
CREATE TABLE BOOK_GENRE (
    BOOK_ID NUMBER(19) NOT NULL,
    GENRE_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_BOOK_GENRE PRIMARY KEY (BOOK_ID, GENRE_ID),
    CONSTRAINT FK_BOOK_GENRE_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    CONSTRAINT FK_BOOK_GENRE_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID)
);

-- Tabela de Relacionamento Usuário x Livro (Com atributos extras)
CREATE TABLE USER_BOOK (
    USER_BOOK_ID NUMBER(19) NOT NULL,
    USER_APP_ID NUMBER(19) NOT NULL,
    BOOK_ID NUMBER(19) NOT NULL,
    REGISTERED_BY NUMBER(1) DEFAULT 0 NOT NULL,
    READ_BY NUMBER(1) DEFAULT 0 NOT NULL,
    WRITTEN_BY NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_BOOK PRIMARY KEY (USER_BOOK_ID),
    CONSTRAINT FK_USER_BOOK_USER FOREIGN KEY (USER_APP_ID) REFERENCES USER_APP(USER_ID),
    CONSTRAINT FK_USER_BOOK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    CONSTRAINT CK_USER_BOOK_REG CHECK (REGISTERED_BY IN (0, 1)),
    CONSTRAINT CK_USER_BOOK_READ CHECK (READ_BY IN (0, 1)),
    CONSTRAINT CK_USER_BOOK_WRITE CHECK (WRITTEN_BY IN (0, 1))
);

- Carga da tabela USER_STATUS (Baseada no UserStatusEnum)
INSERT INTO USER_STATUS (STATUS_ID, NAME) VALUES (1, 'Ativo');
INSERT INTO USER_STATUS (STATUS_ID, NAME) VALUES (2, 'Inativo');
INSERT INTO USER_STATUS (STATUS_ID, NAME) VALUES (3, 'Bloqueado');

-- Carga da tabela GENRE (Baseada no GenreEnum)
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (1, 'Literatura Brasileira');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (2, 'Romance');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (3, 'Distopia');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (4, 'Fantasia');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (5, 'Ficção Científica');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (6, 'Erótico');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (7, 'Drama');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (8, 'Técnico');


ALTER TABLE AUTHOR ADD (
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE BOOK ADD (
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE USER_APP ADD (
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE SEQUENCE SEQ_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE ROLE (
    ROLE_ID NUMBER(19, 0) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_ROLE_NAME UNIQUE (NAME)
);


CREATE TABLE USER_ROLE (
    USER_ID NUMBER(19, 0) NOT NULL,
    ROLE_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES USER_APP(USER_ID),
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);


ALTER TABLE USER_APP ADD (
    LAST_LOGIN TIMESTAMP
);


INSERT INTO ROLE (ROLE_ID, NAME) VALUES (SEQ_ROLE.NEXTVAL, 'ROLE_USER');
INSERT INTO ROLE (ROLE_ID, NAME) VALUES (SEQ_ROLE.NEXTVAL, 'ROLE_ADMIN');



-- 1. Criar a Sequence para os novos IDs da tabela USER_ROLE
CREATE SEQUENCE SEQ_USER_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 2. Remover a chave primária composta antiga (USER_ID + ROLE_ID)
ALTER TABLE USER_ROLE DROP CONSTRAINT PK_USER_ROLE;

-- 3. Adicionar a nova coluna do ID
ALTER TABLE USER_ROLE ADD (
    USER_ROLE_ID NUMBER(19, 0)
);

-- 4. Preencher o ID nos registros que já existem usando a Sequence criada
UPDATE USER_ROLE 
   SET USER_ROLE_ID = SEQ_USER_ROLE.NEXTVAL 
 WHERE USER_ROLE_ID IS NULL;

-- 5. Tornar a nova coluna NOT NULL e definir como Chave Primária (PK)
ALTER TABLE USER_ROLE MODIFY (USER_ROLE_ID NUMBER(19, 0) NOT NULL);
ALTER TABLE USER_ROLE ADD CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ROLE_ID);

-- 6. Adicionar restrição UNIQUE para garantir que um usuário não receba a mesma role duas vezes
ALTER TABLE USER_ROLE ADD CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID);

-- Remover as colunas CREATED_AT e UPDATED_AT da tabela ROLE
ALTER TABLE ROLE DROP (CREATED_AT, UPDATED_AT);

COMMIT;

COMMIT;

