# src/main/resources/gemini.properties
gemini.api.key={segredo}
gemini.prompt.livro=Dado o título de um livro em português, identifique a obra e retorne o seu título original na língua em que foi escrito. Responda estritamente em formato JSON com o seguinte padrão: '{' "originalTitle": "Nome Original do Livro", "originalLanguage": "Idioma" '}' Livro: {0}