url.integration.open.library.by.any=https://openlibrary.org/search.json?q={0}
url.integration.open.libraryb.by.title=https://openlibrary.org/search.json?title={0}
url.integration.open.library.by.author=https://openlibrary.org/search.json?title={0}
url.integration.open.library.authors=https://openlibrary.org/search/authors.json?q={0}
